version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wandering_companions_db
    environment:
      POSTGRES_DB: wandering_companions
      POSTGRES_USER: wandering_user
      POSTGRES_PASSWORD: wandering_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wandering_user -d wandering_companions"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: